// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChZJDhQBNE6nBRI53sjzbHo16Hbv8WeSU',
    appId: '1:933167062902:web:7f75c0425081aca6c86457',
    messagingSenderId: '933167062902',
    projectId: 'luxora-app-6c7c7',
    authDomain: 'luxora-app-6c7c7.firebaseapp.com',
    storageBucket: 'luxora-app-6c7c7.firebasestorage.app',
    measurementId: 'G-3KGYCDB8HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNAR4RZYUCSEm--Fl7jZ7SOa7z6FvpIQw',
    appId: '1:933167062902:android:931723f973a54d1dc86457',
    messagingSenderId: '933167062902',
    projectId: 'luxora-app-6c7c7',
    storageBucket: 'luxora-app-6c7c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcqIoB4Euwv-I19trJwV_WufCrPfu-Wg',
    appId: '1:933167062902:ios:db1a35021b9d0fc4c86457',
    messagingSenderId: '933167062902',
    projectId: 'luxora-app-6c7c7',
    storageBucket: 'luxora-app-6c7c7.firebasestorage.app',
    iosBundleId: 'com.example.luxoraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmcqIoB4Euwv-I19trJwV_WufCrPfu-Wg',
    appId: '1:933167062902:ios:db1a35021b9d0fc4c86457',
    messagingSenderId: '933167062902',
    projectId: 'luxora-app-6c7c7',
    storageBucket: 'luxora-app-6c7c7.firebasestorage.app',
    iosBundleId: 'com.example.luxoraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChZJDhQBNE6nBRI53sjzbHo16Hbv8WeSU',
    appId: '1:933167062902:web:83448fd399908ebac86457',
    messagingSenderId: '933167062902',
    projectId: 'luxora-app-6c7c7',
    authDomain: 'luxora-app-6c7c7.firebaseapp.com',
    storageBucket: 'luxora-app-6c7c7.firebasestorage.app',
    measurementId: 'G-G5TLPZTF66',
  );

}